#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Pig.Resource", IsApplication=true)]

namespace Pig
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PigClasses.Resource.String.ApplicationName = global::Pig.Resource.String.ApplicationName;
			global::PigClasses.Resource.String.Hello = global::Pig.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int edittextcolor = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int labelcolor = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int scorelabelcolor = 2131034114;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int activity_vertical_margin = 2131099649;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Die8Side1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Die8Side2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Die8Side3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Die8Side4 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Die8Side5 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Die8Side6 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Die8Side7 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Die8Side8 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int pigbg = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int Player1ScoreLabel = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int Player1ScoreValue = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int Player1Text = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int Player2ScoreLabel = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int Player2ScoreValue = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int Player2Text = 2131165188;
			
			// aapt resource value: 0x7f07000a
			public const int diceRoll = 2131165194;
			
			// aapt resource value: 0x7f07000f
			public const int endGameButton = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int endTurnButton = 2131165198;
			
			// aapt resource value: 0x7f070000
			public const int frameLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int playerLabel1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int playerLabel2 = 2131165186;
			
			// aapt resource value: 0x7f07000d
			public const int rollDieButton = 2131165197;
			
			// aapt resource value: 0x7f070009
			public const int turnLabel = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int turnPointsLabel = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int turnPointsValue = 2131165196;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040008
			public const int EndTurnText = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int NewGameText = 2130968585;
			
			// aapt resource value: 0x7f040002
			public const int PlayerLabel1 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int PlayerLabel2 = 2130968579;
			
			// aapt resource value: 0x7f040007
			public const int RollButtonText = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int scoreText = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int turnPointsText = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int turnText = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
